#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

echo -e "\n                  欢迎使用 V2Proxy 管理程序 Author:南音"
echo ""
echo -e "\n1.服务管理"
echo -e "\n2.更改配置"
echo -e "\n3.查看配置信息"
echo -e "\n4.生成vmess链接"
echo -e "\n5.卸载V2Ray程序"
echo -e "\n请输入数字选择功能(按回车键退出)："

while :; do echo
	read -p "请选择： " choice
	if [[ ! $choice =~ ^[1-4]$ ]]; then
        if [[ -z ${choice} ]];then
            exit 0
        fi
		echo "输入错误! 请输入正确的数字!"
	else
		break	
	fi
done

if [[ ${choice} == 1 ]]; then
    echo "1.启动服务"
    echo "2.停止服务"
    echo "3.重启服务"
    echo "4.运行状态"
    echo "5.运行日志"
    while :; do echo
	    read -p "请选择： " schoice
	    if [[ ! $schoice =~ ^[1-5]$ ]]; then
            if [[ -z ${schoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
		    break
	    fi
    done
    if [[ ${schoice} == 1 ]]; then
        service v2ray start
        python /usr/local/V2Proxy/openport.py
        python /usr/local/V2Proxy/genclient.py
        echo "服务启动成功！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 2 ]]; then
        service v2ray stop
        echo "服务停止成功！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 3 ]]; then
        service v2ray restart
        python /usr/local/V2Proxy/openport.py
        python /usr/local/V2Proxy/genclient.py
        echo "服务已重启！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 4 ]]; then
        service v2ray status
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 5 ]]; then
        echo "按Ctrl + C 可以退出日志功能"
        echo ""
        tail -f /var/log/v2ray/access.log
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 2 ]]; then
    echo ""
    echo "1.更改端口"
    echo "2.更改UUID"
    echo "3.更改AlterId"
    echo "4.更改加密方式"
    echo "5.更改传输方式"
    echo "6.更改TLS设置"
    echo ""
    echo "请输入数字选择功能："

    while :; do echo
	    read -p "请选择： " changechoice
	    if [[ ! $changechoice =~ ^[1-5]$ ]]; then
            if [[ -z ${changechoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
		    break
	    fi
    done
    
    if [[ ${changechoice} == 1 ]]; then
        python /usr/local/V2Proxy/changeport.py
        python /usr/local/V2Proxy/genclient.py
	python /usr/local/V2Proxy/openport.py
        echo ""
        echo "端口修改成功！"
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changechoice} == 2 ]]; then
        python /usr/local/V2Proxy/changeuuid.py
        python /usr/local/V2Proxy/genclient.py
        echo ""
        echo "UUID修改成功！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${changechoice} == 3 ]]; then
        python /usr/local/V2Proxy/changealterId.py
        python /usr/local/V2Proxy/genclient.py
        echo ""
        echo "AlterId修改成功！"
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changechoice} == 4 ]]; then
        python /usr/local/V2Proxy/changesecurity.py
        python /usr/local/V2Proxy/genclient.py
        echo ""
        echo "加密方式修改成功！"
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changechoice} == 5 ]]; then
        python /usr/local/V2Proxy/changestream.py
        python /usr/local/V2Proxy/genclient.py
        echo ""
        echo "传输模式修改成功！"
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changechoice} == 6 ]]; then
        python /usr/local/V2Proxy/changetls.py
        python /usr/local/V2Proxy/genclient.py
        echo ""
        echo "TLS设置修改成功！"
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 3 ]]; then
    python /usr/local/V2Proxy/serverinfo.py
    bash /usr/local/bin/v2ray
fi

if [[ ${choice} == 4 ]]; then
    echo "目前仅支持Bifrostv的vmess链接"
    python /usr/local/V2Proxy/genclient.py
    bash /usr/local/bin/v2ray
fi
if [[ ${choice} == 5 ]]; then
    python /usr/local/V2Proxy/uninstall.sh
    bash /usr/local/bin/v2ray
fi
